server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices
  application:
    name: RATINGSERVICE

  config:
    import: optional:configserver:http://localhost:8084